#!/bin/bash

if [[ `php -r "echo version_compare(PHP_VERSION, '7.4.0', '>=');"` ]]; then
    cd build/php8
elif [[ `php -r "echo version_compare(PHP_VERSION, '7.0.0', '>=');"` ]]; then
    cd build/php7
else
    cd build/php5
fi

source ./install
