#!/bin/bash
export CC="gcc"
directory=`pwd`
if [ -f Makefile ]; then
        sudo make --silent clean
        sudo /usr/local/bin/phpize --silent --clean
fi
/usr/local/bin/phpize --silent
sleep 1
$directory/configure --silent --enable-ice
make --silent && sudo make --silent install
