name: Ice Framework CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1']
        include:
          - name: focal
            os: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gettext, gd, intl, json, mbstring
          tools: pecl, phpize, php-config
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

