name: Ice Framework CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1']
        include:
          - name: focal
            os: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gettext, gd, intl, json, mbstring
          tools: pecl, phpize, php-config
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: composer install --prefer-source --no-scripts

      - name: Compile
        shell: bash
        run: |
          (cd vendor/iceframework/zephir-parser; ./install; phpenv config-add tests/ci/zephir_parser.ini)
          php -d memory_limit=512M ./vendor/bin/zephir generate
          (mkdir generated; cp -a ext/. generated)
          (cd ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden -DZEPHIR_RELEASE=1"; phpize && ./configure --enable-ice && make -j2 && make install && phpenv config-add ../tests/ci/ice.ini)
